
import { Host } from './types';

export const NUCLEUS_HOSTS: Host[] = [
  { id: 'jh-01', name: 'nucleus-jump-01', ip: '10.0.1.5', status: 'online', region: 'us-east-1' },
  { id: 'jh-02', name: 'nucleus-jump-02', ip: '10.0.1.6', status: 'online', region: 'eu-west-1' },
  { id: 'prod-web-01', name: 'web-prod-01', ip: '172.16.0.10', status: 'online', region: 'us-east-1' },
];

export const OWASP_TOOLS = [
  'ZAP Scanner',
  'Nikto',
  'Sqlmap (Automated)',
  'SSLScan',
  'Dirb'
];

export const RAW_ETC_HOSTS = `
t6f-hermes
ose-cbc-01
ose-mvnx-01
ose-afrit-01
ose-velocity-parklands
IDMAIM01
ose-e4mesh-01
ose-velocity-london-01
ose-velocity-london-02
ose-velocity-london-ld6
ose-fem-01
ose-webberwentzel-01
ose-webberwentzel-02
ose-econet-lesotho-tacacs-01
ose-econet-lesotho-kenya-01
ose-saica-03
ose-st-cyprians-02
ose-safetysa-ac-dbn
ose-safetysa-east-london
ose-safetysa-polokwane
ose-safetysa-witbank
ose-safetysa-secunda
ose-safetysa-nelspruit
ose-safetysa-ac-oudts
ose-safetysa-bloemfontein
ose-safetysa-rustenburg
ose-safetysa-ac-mid
ose-safetysa-centurion
ose-safetysa-midrand
ose-safetysa-boksburg
ose-safetysa-vanderbijlpark
ose-safetysa-ct
ose-safetysa-kathu
ose-safetysa-pe
ose-safetysa-ac-pe
ose-safetysa-richardsbay
ose-safetysa-durban-westville
ose-safetysa-ac-cpt
ose-lancet-ghana-01
ose-lancet-nigeria-01
ose-lancet-zambia-01
ose-lancet-uganda-01
ose-lancet-tanzania-01
ose-lancet-rwanda-01
ose-lancet-zimbabwe-01
ose-lancet-kenya-01
ose-lancet-mozambique-01
ose-medis-kzn-01
ose-cch-01
ose-global-layer-01
ose-sodecia-01
OSE-01-STCYPRIANS
ose-comcorp-01
ose-ballito-isp-01
ose-khanya-africa-01
ose-shisanyama-01
ose-easypay-01
ose-agsa-01
ose-econet-lesotho-01
ose-medikredit-01
ose-universal
ose-01-paycorp
ose-02-paycorp
ose-saicom
ose-ideacandy-01
mc-jhb-1
ose-ionline-aws-01
ose-ionline-aws-02
ose-recharger-01
ose-medis-01
ose-fibregeeks
ose-pageautomation
ose-02-siliconsky
ose-newsclip
ose-trinity-telecom
ose-metrofibre-01
ose-gic-01
ose-ideacandy-02
ose-hiltoncollege-01
ose-stpetersprep-01
ose-auditorgen
ose-siliconsky-usa-01
ose-ignition-01
ose-kazang-01
ose-vodacomlesotho-01
ose-cmc-tacacs-01
ose-velocity-isando-01
ose-veza-ict-01
ose-comsol-01
ose-comsol-02
ose-gigawave-01
ose-medis-02
ose-com
probe01-conco
ose-echo-jhb-tacacs
ose-echo-cpt-tacacs
ose-echo-cpt-needlecast
probe01-hollywood
ose-mix_telematics
jumo-ose-1
ose-tnm
ose-velocity-claremont
ose-fnet-01
ose-velocity-isando
ose-gz_industries
ose-citylodge-1
ose-echo-01
ose-ekurhuleni-auth
ose-echo-02
saica-ose-vm
ose-saica-01
ose-01-afrihost
ose-mix-telematics-Africa-01
ose-minerals-council-01
ose-velocity-claremont-02
Cerba-Lancet-Ghana-OSE
Cerba-Lancet-mozambique-OSE
Cerba-Lancet-zambia-OSE
Cerba-Lancet-nigeria-OSE
Cerba-Lancet-uganda-OSE
Cerba-Lancet-tanzania-OSE
Cerba-Lancet-rwanda-OSE
Cerba-Lancet-zimbabwe-OSE
Cerba-Lancet-Kenya-OSE
ose-ignition-ct-01
ose-01-silicon-sky
ose_oceana_cpt
ose-webafrica-01
`;
